version: "3.3"

services:


  social:
    build:
      context: .
    image: vaiot-lottery-service
    env_file: docker-compose.env
    environment:
      SERVICES: social
    networks:
      -  vaiot-api-gateway_internal

  lottery:
    build:
      context: .
    image: vaiot-lottery-service
    env_file: docker-compose.env
    environment:
      SERVICES: lottery
    depends_on:
      - social
    networks:
      -  vaiot-api-gateway_internal


networks:
  vaiot-api-gateway_internal:
    external: true

volumes:
  data:
