version: "3.3"

services:

  lottery:
    platform: linux/amd64
    build:
      context: .
    image: vaiot-lottery-service
    env_file: 
      - docker-compose.env
      - .env
    environment:
      SERVICES: lottery
    depends_on:
      - twitter
      - telegram
    networks:
      -  vaiot-api-gateway_internal

  twitter:
    platform: linux/amd64
    build:
      context: .
    image: vaiot-lottery-service
    env_file: 
      - docker-compose.env
      - .env
    environment:
      SERVICES: twitter
    networks:
      -  vaiot-api-gateway_internal

  telegram:
    platform: linux/amd64
    build:
      context: .
    image: vaiot-lottery-service
    env_file: 
      - docker-compose.env
      - .env
    environment:
      SERVICES: telegram
    networks:
      -  vaiot-api-gateway_internal


networks:
  vaiot-api-gateway_internal:
    external: true

volumes:
  data:
