#########################################################
# Common Environment variables ConfigMap
#########################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
data:
  NAMESPACE: ""
  LOGLEVEL: info
  SERVICEDIR: services
---
#########################################################
# Lottery service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery
spec:
  selector:
    matchLabels:
      app: lottery
  replicas: 1
  template:
    metadata:
      labels:
        app: lottery
    spec:
      containers:
      - name: lottery
        image: vaiotcr.azurecr.io/vaiot-lottery-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: lottery

---
#########################################################
# Twitter service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
spec:
  selector:
    matchLabels:
      app: twitter
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
      - name: twitter
        image: vaiotcr.azurecr.io/vaiot-lottery-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: twitter
---
#########################################################
# Telegram service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram
spec:
  selector:
    matchLabels:
      app: telegram
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram
    spec:
      containers:
      - name: telegram
        image: vaiotcr.azurecr.io/vaiot-lottery-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: telegram